# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e67bc408dbb4142fe11cb37694570d3ba06c946a499f8857e7c8a9576b54d94b070ec7b15f6b1d6fddb064cfb0dcd91dc44cd49b83e8da3c64ec36fcb4fb5314

test:
  secret_key_base: e8b5058de549db2c9713f83226f8d913ef9b007956f1d0b0db6fa55c3d973078a330bb174a2798e9a400ccdb6738812cc1450697176e1a65eb239e5f25876878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
